### ISSUE TITLE
Images added to the wrong cards

### ISSUE THREAD

**Issue by mahnac** [9dogs/notion-anki-sync#11]
Two times I have experienced this now. The image I created for one card is added to another card. which is very confusing.

**Comment by mahnac** [comment]
I think the bug is related to moving the toggle lists around.

**Comment by 9dogs** [comment]
Can you export the page to HTML manually and check if the image is in the right place? Sadly Notion export sometimes mixes up the content of the toggles. If that's the issue, the only way to resolve it is to use Notion API (which is planned but has no ETA yet).

**Comment by mahnac** [comment]
Yes, I will try that the next time it happens and report back.
