### ISSUE TITLE
Looks like the add-on no longer works

### ISSUE THREAD

**Issue by louishermand** [9dogs/notion-anki-sync#18]
Hi, I've been using this addon for months and it's really great, but since few week it's no longer working. It seems that i'm not the only one with this issue.

When oppening Anki, I've got the following message :

"Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Notion Toggles Loader⁩':
⁨Traceback (most recent call last):
File "aqt.addons", line 247, in loadAddons
File "/home/user/.var/app/net.ankiweb.Anki/data/Anki2/addons21/1940767534/__init__.py", line 12, in <module>
from aqt.hooks_gen import main_window_did_init
ModuleNotFoundError: No module named 'aqt.hooks_gen' "

Could you help me with this issue ?
Thank you !

**Comment by 9dogs** [comment]
Oh, thanks for reporting! I will take a look shortly.

**Comment by 9dogs** [comment]
@louishermand, I've updated the addon, can you check if it works now? I couldn't use "Update All" option in Anki -- for some reason it didn't update anything at all. I had to select "Notion Toggles Loader" alone and then it worked.

**Comment by louishermand** [comment]
It works perfectly, thank you very much @9dogs ! :)
