### ISSUE TITLE
Unable to load Notion toggles - seeing an error saying "cannot export <page-id>: Invalid token"

### ISSUE THREAD

**Issue by rahulbagai** [9dogs/notion-anki-sync#21]
I am having an issue with loading Notion toggles from the Mac Anki app. Every time I try to load them, I get an error message that says "Cannot export <page-id>: Invalid token". I have tried reinstalling the notion addon, Anki, and clearing my Anki directories from the disk, but the issue still persists.

Steps to Reproduce:
1. Install Anki on macOS (Apple Silicon 2.1.61 QT6)
2. Install the Notion toggle.
3. Update the configuration with page_id and Notion_token.
4. Attempt to load the Notion toggle.
5. Observe the error message that says "cannot export <page-id>: Invalid token".

Expected Behavior:
The Notion toggles should load without any errors.

Actual Behavior:
The toggles fail to load and an error message saying "cannot export <page-id>: Invalid token" is displayed.

Additional Information
- MacBook (Chip - Apple M1)
- Notions 

Please let me know in case any other details are required.

**Comment by 9dogs** [comment]
Can you verify your token value? It should start with `v02%3Auser_token_or_cookies...`

**Comment by rahulbagai** [comment]
> Can you verify your token value? It should start with `v02%3Auser_token_or_cookies...`

@9dogs This issue got resolved. I was using the old token value from notion, and once I updated that to the new one, the issue got fixed. thanks for the followup!
