### ISSUE TITLE
Pyqt6

### ISSUE THREAD

**Issue by zxyacg** [9dogs/notion-anki-sync#23]
![image](https://github.com/9dogs/notion-anki-sync/assets/76837288/dee85d4d-6546-4f75-b9e8-6d01e66cd655)

I get this error when I start anki, but I have PyQt6 installed, what is the problem.

**Comment by 9dogs** [comment]
@zxyacg, are you using the Qt5 version of Anki? There are two options on the Anki download page, could you try the one with Qt6?

**Comment by zxyacg** [comment]
@9dogs ,
Firstly, I clicked on Load notes, and the following error occurred
![image](https://github.com/9dogs/notion-anki-sync/assets/76837288/1439fa7e-9892-44a9-8562-514ccb61e97b)
Secondly, I added this
![image](https://github.com/9dogs/notion-anki-sync/assets/76837288/53d5e90e-1cb2-4b1f-bced-0fa920a7cdcc)
Finally, the following error appears, what should I do to solve it, thanks
![image](https://github.com/9dogs/notion-anki-sync/assets/76837288/595e4354-e458-4b56-87bf-23e814a5725e)
