### ISSUE TITLE
Integrate the new Notion API

### ISSUE THREAD

**Issue by leon-cgn** [9dogs/notion-anki-sync#4]
hey, 
do you plan to integrate the new Notion API? I understand, that you parse the html for now. 
Getting the page and extract the toogles could be easier: https://developers.notion.com/reference/get-page

keep up the good work :)

**Comment by 9dogs** [comment]
Sup. I guess it has to be done eventually. 
Kicking in an export task and parsing HTML is an ugly (though viable) solution. With the new API, HTML should be constructed by hand, which is not pretty as well. I'm thinking of postponing the transition at least until Notion's API comes out of the beta.
