### ISSUE TITLE
Load fail

### ISSUE THREAD

**Issue by jejoja6206** [9dogs/notion-anki-sync#5]
Hi i received this error message:
![image](https://user-images.githubusercontent.com/85090055/120134625-88da5100-c19c-11eb-8ade-6b0cc41c5f5f.png)

I followed the steps correctly. I dont know what happened

**Comment by 9dogs** [comment]
Hi! This error message comes straight from the Notion API. 
Can you double-check your block id? It usually comes in form of `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` (8-4-4-4-12), and yours has 7-4-4-4-13.

**Comment by jejoja6206** [comment]
Yes i have checked and i have 32 characters. Im getting this error message
below:
Error
An error occurred. Please start Anki while holding down the shift key,
which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools >
Add-ons menu item to disable some add-ons and restart Anki, repeating until
you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please
report the issue on the add-on support site.
Debug info:
Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-05-30 21:21:19

Caught exception:
Traceback (most recent call last):
  File
"C:\Users\jessi\AppData\Roaming\Anki2\addons21\1940767534\__init__.py",
line 395, in run
    notes += extract_notes_data(
  File
"C:\Users\jessi\AppData\Roaming\Anki2\addons21\1940767534\parser.py", line
365, in extract_notes_data
    note = NoteDataExtractor.extract_note(
  File
"C:\Users\jessi\AppData\Roaming\Anki2\addons21\1940767534\parser.py", line
336, in extract_note
    parser.feed(html)
  File "html\parser.py", line 111, in feed
  File "html\parser.py", line 171, in goahead
  File "html\parser.py", line 343, in parse_starttag
  File "html\parser.py", line 427, in handle_startendtag
  File
"C:\Users\jessi\AppData\Roaming\Anki2\addons21\1940767534\parser.py", line
226, in handle_starttag
    data=abs_path.read_bytes(),
  File "pathlib.py", line 1228, in read_bytes
  File "pathlib.py", line 1221, in open
  File "pathlib.py", line 1077, in _opener
OSError: [Errno 22] Invalid argument:
'C:\\Users\\jessi\\AppData\\Local\\Temp\\tmpxud8u7a8\\https:\\i.pinimg.com
\\originals\\70\\cf\\ac\\70cfaca35763389cafcc347e2d0e4fe5.jpg'

**Comment by jejoja6206** [comment]
I also disabled all addons and added them back one by one and still got the error message

**Comment by jejoja6206** [comment]
i seemed to have found the problem a few toggles in notion with images were causing the issue

**Comment by 9dogs** [comment]
I guess you had image embedds in these toggles? I guess the plugin should account for this case, thanks for reporting.
