### ISSUE TITLE
User cannot access block, or it does not exist.

### ISSUE THREAD

**Issue by ineedmoreoxytocin** [9dogs/notion-anki-sync#6]
![image](https://user-images.githubusercontent.com/62963741/128212572-6d7fa20c-d806-4634-9501-7b75498fae6c.png)
I followed every step and made my notes public too. Any ideas on what I should do?
Also, is it possible to switch to the official Notion API, since it is released now?

**Comment by 9dogs** [comment]
Could you please set `"debug": true` in the addon config, reproduce the error, and then attach the log file. It should be around
`~/.local/share/Anki2/addons21/1940767534/log.txt`.

As for the transition to the official Notion API, it's definitely on my to-do list, but it's quite a big task, so I can't give you any time estimate.
